### ISSUE TITLE
Ollama統合サービス実装

### ISSUE THREAD

**Issue by Yamamoto1012** [Yamamoto1012/KIT-VRM-ChatAgent#86]
# サブタスク02: Ollama統合サービス実装

## 1. 背景 (Background)

* **なぜこのタスクが必要か？** プライバシーとコスト効率を重視したローカルLLMとして、Ollama統合が必要である。101-workspace/mcp-wsにはMCPプロトコルとOllamaが実装されているが、MCPは複雑すぎるため、Ollama部分のみを簡素化して統合する。
* **現状の課題:** 
  * OpenAI APIのコスト負担（特に大量利用時）
  * 外部API依存によるプライバシー懸念
  * インターネット接続が不安定な環境での利用制限
  * M1Mac（Metal）とLinux（CUDA）の異なるGPU環境対応
* **ビジネス価値:** コスト効率とプライバシーを重視したローカルLLMオプションを提供し、様々な運用シナリオに対応する

## 2. 詳細 (Details)

* **何を実装するのか？** Ollamaを使用したローカルLLM統合サービスを新規実装を行う：

#### 2.1 Ollama統合機能
```python
# Ollama基本設定
OLLAMA_CONFIG = {
    "base_url": "http://localhost:11434",  # M1Mac
    "models": {
        "default": "mistral:7b-instruct",
        "lightweight": "tinyllama:1.1b",
        "japanese": "elyza:jp-7b"
    },
    "timeout": 30
}
```

#### 2.2 環境自動検出・最適化
```python
import platform
import subprocess
from typing import Dict, Any

def detect_environment() -> Dict[str, Any]:
    """実行環境の自動検出"""
    machine = platform.machine()
    system = platform.system()
    
    if machine == "arm64" and system == "Darwin":  # M1Mac
        return {
            "platform": "m1mac",
            "gpu": "metal",
            "ollama_url": "http://localhost:11434",
            "recommended_models": ["mistral:7b-instruct", "tinyllama:1.1b"]
        }
    elif system == "Linux":
        gpu_available = check_cuda_availability()
        return {
            "platform": "linux",
            "gpu": "cuda" if gpu_available else "cpu",
            "ollama_url": "http://ollama:11434",  # Docker service
            "recommended_models": ["mistral:7b-instruct", "llama2:7b"]
        }
    else:
        return {
            "platform": "other",
            "gpu": "cpu",
            "ollama_url": "http://localhost:11434",
            "recommended_models": ["tinyllama:1.1b"]
        }

def check_cuda_availability() -> bool:
    """CUDA利用可能性チェック"""
    try:
        result = subprocess.run(["nvidia-smi"], capture_output=True, text=True)
        return result.returncode == 0
    except FileNotFoundError:
        return False
```

#### 2.3 APIエンドポイント設計
```python
# 基本テキスト生成
POST /llm/ollama/generate
{
    "prompt": "金沢工業大学について説明して",
    "model": "mistral:7b-instruct",  # オプション
    "max_tokens": 500,
    "temperature": 0.7
}

# チャット形式対話
POST /llm/ollama/chat
{
    "messages": [
        {"role": "user", "content": "こんにちは"}
    ],
    "model": "mistral:7b-instruct",
    "stream": false
}

# モデル管理
GET /llm/ollama/models
# -> 利用可能モデル一覧

POST /llm/ollama/pull_model
{
    "model": "mistral:7b-instruct"
}

# 環境状態確認
GET /llama/ollama/status
# -> Ollama接続状態、モデル状態、GPU使用状況
```

#### 2.4 M1Mac開発環境対応
```yaml
# M1Mac最適化設定
m1mac_config:
  gpu_acceleration: metal
  memory_optimization: true
  recommended_models:
    - "mistral:7b-instruct"    # 7Bパラメータ
    - "tinyllama:1.1b"         # 軽量版
  ollama_installation:
    method: homebrew
    command: "brew install ollama"
  docker_platform: "linux/arm64"
```

#### 2.5 Linuxクラウド本番環境対応
```yaml
# Linux最適化設定
linux_config:
  gpu_acceleration: cuda
  memory_optimization: true
  recommended_models:
    - "mistral:7b-instruct"    # 7Bパラメータ
    - "llama2:7b"              # Meta公式
  ollama_installation:
    method: docker
    service: ollama:latest
  docker_platform: "linux/amd64"
```

#### 2.6 統一Ollamaサービス実装
```python
import httpx
import asyncio
from typing import Optional, List, Dict, Any

class OllamaService:
    def __init__(self):
        self.env_config = detect_environment()
        self.base_url = self.env_config["ollama_url"]
        self.client = httpx.AsyncClient(timeout=30.0)
    
    async def generate(
        self, 
        prompt: str, 
        model: Optional[str] = None,
        **kwargs
    ) -> Dict[str, Any]:
        """テキスト生成"""
        model = model or self.env_config["recommended_models"][0]
        
        payload = {
            "model": model,
            "prompt": prompt,
            "stream": False,
            **kwargs
        }
        
        response = await self.client.post(
            f"{self.base_url}/api/generate",
            json=payload
        )
        return response.json()
    
    async def chat(
        self,
        messages: List[Dict[str, str]],
        model: Optional[str] = None,
        **kwargs
    ) -> Dict[str, Any]:
        """チャット形式対話"""
        model = model or self.env_config["recommended_models"][0]
        
        payload = {
            "model": model,
            "messages": messages,
            "stream": False,
            **kwargs
        }
        
        response = await self.client.post(
            f"{self.base_url}/api/chat",
            json=payload
        )
        return response.json()
    
    async def list_models(self) -> List[Dict[str, Any]]:
        """利用可能モデル一覧"""
        response = await self.client.get(f"{self.base_url}/api/tags")
        return response.json().get("models", [])
    
    async def pull_model(self, model: str) -> bool:
        """モデルダウンロード"""
        payload = {"name": model}
        response = await self.client.post(
            f"{self.base_url}/api/pull",
            json=payload
        )
        return response.status_code == 200
    
    async def check_health(self) -> Dict[str, Any]:
        """Ollama健康状態チェック"""
        try:
            response = await self.client.get(f"{self.base_url}/api/tags")
            models = response.json().get("models", [])
            return {
                "status": "healthy",
                "available_models": len(models),
                "platform": self.env_config["platform"],
                "gpu": self.env_config["gpu"]
            }
        except Exception as e:
            return {
                "status": "unhealthy", 
                "error": str(e),
                "platform": self.env_config["platform"]
            }
```

### 3.1 機能要件
* ✅ M1Mac（Metal）とLinux（CUDA）両環境でのOllama動作
* ✅ 環境自動検出による最適化設定
* ✅ 基本的なテキスト生成・チャット機能
* ✅ モデル管理（ダウンロード・一覧）機能
* ✅ Ollama健康状態監視

### 3.2 性能要件
* **レスポンス時間**: 
  - 短文生成（50トークン）: 5秒以内
  - 中文生成（200トークン）: 15秒以内
  - モデル切り替え: 30秒以内
* **安定性**: Ollama接続エラー時の適切なフォールバック
* **メモリ効率**: GPU使用量の監視・制御

### 3.3 環境対応要件
* ✅ M1Mac: Metal GPU加速対応
* ✅ Linux: CUDA GPU加速対応（オプション）
* ✅ Docker Compose統合
* ✅ プラットフォーム自動検出

### 3.4 統合要件
* ✅ backend/fast-apiへの統合
* ✅ OpenAI RAGサービスとの共存
* ✅ 統一API形式（OpenAI互換）

#### Phase 1: Ollama基盤実装
1. **環境検出**: プラットフォーム自動判定
2. **Ollama接続**: HTTP APIクライアント実装
3. **基本機能**: テキスト生成・チャット

#### Phase 2: 環境最適化
1. **M1Mac対応**: Metal GPU最適化
2. **Linux対応**: CUDA GPU最適化
3. **Docker統合**: サービス化

#### Phase 3: 管理機能・監視
1. **モデル管理**: ダウンロード・切り替え
2. **監視機能**: 健康状態・GPU使用量
3. **エラー処理**: 堅牢なフォールバック

### 4.2 技術スタック
```yaml
# 必要なライブラリ
dependencies:
  - httpx>=0.24.0         # Ollama HTTP client
  - asyncio               # 非同期処理
  - fastapi               # API framework
  - psutil                # システム監視
  - docker                # Docker統合

# 環境設定
ollama_setup:
  m1mac:
    installation: "brew install ollama"
    gpu: metal
    models: ["mistral:7b-instruct", "tinyllama:1.1b"]
  linux:
    installation: docker
    gpu: cuda
    models: ["mistral:7b-instruct", "llama2:7b"]
```

### 4.3 除外機能（MCPプロトコル関連）
* **MCPプロトコル**: 複雑性に対して価値が不明のため除外
* **複雑なコネクション管理**: 単純なHTTP APIで十分
* **カスタムプロトコル**: 標準的なREST APIで代替

### 技術的考慮事項
* **GPUメモリ管理**: AivisSpeechとの共存考慮
* **モデルサイズ**: 環境に応じた適切なモデル選択
* **レイテンシ**: ローカル実行による低遅延特性活用
* **プライバシー**: 完全ローカル実行による情報保護

### 運用考慮事項
* **コスト削減**: OpenAI API料金削減効果
* **オフライン対応**: インターネット接続不要
* **モデル更新**: 定期的なモデルアップデート戦略
* **容量管理**: モデルファイルのストレージ管理

### M1Mac特化最適化
* **Apple Silicon**: Metal Performance Shaders活用
* **メモリ統合**: Unified Memory Architecture対応
* **電力効率**: M1/M2チップの効率的利用

### Linux本番環境最適化
* **CUDA**: NVIDIA GPU最適化（利用可能時）
* **コンテナ**: Docker/Kubernetes対応
* **スケーリング**: 水平スケーリング準備

### 将来拡張準備
* **ストリーミング**: リアルタイムレスポンス対応
* **ファインチューニング**: カスタムモデル対応準備
* **多言語**: 多言語モデル対応
